---
# tasks file for install_docker_engine
#  - name: install one specific version of Apache
#    yum:
#      name: oracle-softwarecollection-release-el7  
#      state: present

  - block:
#      - name:
#        debug:
#          msg: "[Worker] K8S_TOKEN_HOLDER K8S token is {{ hostvars['K8S_TOKEN_HOLDER']['token'] }}"
#      - name:
#        debug:
#          msg: "[Worker] K8S_TOKEN_HOLDER K8S Hash is  {{ hostvars['K8S_TOKEN_HOLDER']['hash'] }}"
#      - name:
#        debug:
#          msg: "[Worker] K8S_TOKEN_HOLDER K8S Master is  {{ hostvars['K8S_MASTER_NODE_IP']['ip'] }}"

      - name: enable OL7 Addon Repo
        ini_file:
          dest: "{{ oracle_yum_docker_repo_file }}"
          section: "{{ oracle_docker_reponame }}"
          option: enabled
          value: 1

      - name: Check the kubeadm  package is installed
        yum:
          name: kubeadm
          state: present

      - name: Check the kubelet package is installed
        yum:
          name: kubelet
          state: present

      - name: Check the kubectl  package is installed
        yum:
          name: kubectl
          state: present

#      - name: Kubeadm join on worker node o join master
#       shell: >
#         kubeadm join --token={{ hostvars['K8S_TOKEN_HOLDER']['token'] }}
#         --discovery-token-ca-cert-hash sha256:{{ hostvars['K8S_TOKEN_HOLDER']['hash'] }}
#         {{ hostvars['K8S_MASTER_NODE_IP']['ip'] }}:{{K8S_API_SERCURE_PORT}}
