#
---
apiVersion: v1
kind: Service
metadata:
 name: cra3ml-svc
spec:
 type: LoadBalancer
 selector:
   app: cra3ml-dep
 ports:
 - port: 8080
   name: app3-appport
 - port: 8081
   name: app3-onslport
 - port: 22
   name: app3-sshport
 - port: 9090
   name: app3-pmport
 - port: 3001
   name: app3-reactport
 - port: 5901
   name: app3-vncport
 selector:
   app: cra3ml-dep
