#
---
apiVersion: v1
kind: Service
metadata:
 name: cra3app
spec:
 type: LoadBalancer
 selector:
   app: cra3app-dep
 ports:
 - name: app3-apport
   protocol: TCP
   port: 8080
   targetPort: app3-apport
 - name: app3-sshport
   protocol: TCP
   port: 22 
   targetPort: app3-sshport
 - name: app3-pmport  
   protocol: TCP
   port: 9090
   targetPort: app3-pmport
 - name: app3-reactport 
   protocol: TCP
   port: 3001
   targetPort: app3-reactport
 - name: app3-vncport 
   protocol: TCP
   port: 5901
   targetPort: app3-vncport
 - name: app3-https
   protocol: TCP
   port: 443
   targetPort: app3-https
 - name: app3-http
   protocol: TCP
   port: 80
   targetPort: app3-http
