#
---
apiVersion: v1
kind: Service
metadata:
 name: cra3ml
spec:
 type: LoadBalancer
 selector:
   app: cra3ml-dep
 ports:
 - containerPort: 8080
   name: app3-appport
 - containerPort: 8081
   name: app3-onslport
 - containerPort: 22
   name: app3-sshport
 - containerPort: 9090
   name: app3-pmport
 - containerPort: 3001
   name: app3-reactport
 - containerPort: 5901
   name: app3-vncport
 selector:
   app: cra3ml-dep
