apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pg-sadapter 
spec:
  template:
    metadata:
      labels:
        app: pg-sadapter
    spec:
      containers:
      - name: pg-sadapter
        image: timescale/prometheus-postgresql-adapter:latest 
        imagePullPolicy: "IfNotPresent"
        args: ["-pg-host=pg_prometheus, -pg-password=secret, -pg-prometheus-log-samples"] 
        ports:
        - containerPort: 9201 
          name: pgs-dbport
      nodeSelector:
       failure-domain.beta.kubernetes.io/zone: PHX-AD-1
---
 apiVersion: v1
 kind: Service
 metadata:
   name: pg-sadapters-lb
 spec:
  type: LoadBalancer
  selector:
    app: pg-sadapters
  ports:
    - name: pgs-dbport
      protocol: TCP
      port: 9201
      targetPort: pgs-dbport
  selector:
    app: pg-sadapters
