---
# tasks file for configure_docker_env
  - name: Modifying Sysctl.conf
    sysctl:
      name: fs.file-max
      value: "{{ oracle_rac_fs_file_max }}"
      state: present
      reload: no

#Set net.core.rmem_max to 4194304 in /etc/sysctl.conf
  - name: Modifying Sysctl.conf
    sysctl:
      name: net.core.rmem_max
      value: "{{ oracle_rac_net_core_rmem_max }}"
      state: present
      reload: yes

#Set net.core.wmem_max to 1048576  in /etc/sysctl.conf
  - name: Modifying Sysctl.conf
    sysctl:
      name: net.core.wmem_max
      value: "{{ oracle_rac_net_core_wmem_max }}"
      state: present
      reload: yes

#Set net.core.wmem_default to 262144 in /etc/sysctl.conf
  - name: Modifying Sysctl.conf
    sysctl:
      name: net.core.wmem_default
      value: "{{ oracle_rac_net_core_wmem_default }}"
      state: present
      reload: yes

#Set net.core.rmem_default to 262144 in /etc/sysctl.conf
  - name: Modifying Sysctl.conf
    sysctl:
      name: net.core.rmem_default
      value: "{{ oracle_rac_net_core_rmem_default }}"
      state: present
      reload: yes

#Set net.ipv4.ip_forward to 1 in /etc/sysctl.conf
#  - name: Modifying Sysctl.conf
#    sysctl:
#      name: net.ipv4.ip_forward
#      value: "{{ oracle_rac_net_ipv4_ip_forward  }}"
#      state: present
#      reload: yes

#Set net.ipv4.conf.docker0.forwarding to 1 in /etc/sysctl.conf
#  - name: Modifying Sysctl.conf
#    sysctl:
#      name: net.ipv4.conf.docker0.forwarding
#      value: "{{ oracle_net_ipv4_conf_docker0_forwarding  }}"
#      state: present
#      reload: yes

#Set net.ipv4.conf.eth0.forwarding  to 1 in /etc/sysctl.conf
#  - name: Modifying Sysctl.conf
#    sysctl:
#      name: net.ipv4.conf.eth0.forwarding
     # value: "{{ oracle_net_ipv4_conf_eth0_forwarding  }}"
     # state: present
     # reload: yes

#Set net.ipv4.conf.lo.forwarding to 1 in /etc/sysctl.conf
#  - name: Modifying Sysctl.conf
#    sysctl:
#      name: net.ipv4.conf.lo.forwarding
#      value: "{{ oracle_net_ipv4_conf_lo_forwarding  }}"
#      state: present
#      reload: yes

# Changing SELINUX to permissive mode
  - name: Changing SELinux to permissive mode
    selinux:
      policy: targeted
      state: permissive

  - name: stop service firewalld on Oracle Linux OCi Compute, if running
    systemd:
      name: firewalld
      state: stopped
      enabled: no
